contact_links:
  - name: Ask a question
    url: https://github.com/mc2-universe/faya/discussions/new?category=hello
    about: Please post questions, and ideas in discussions.
  - name: Questions and ideas
    url: https://github.com/mc2-universe/faya/discussions/new/choose
    about: Please post questions, and ideas in discussions.
